server:
  port: 8090

#----------------------------#
#------[BASE DE DATO DEV]----#
#----------------------------#
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/platzi-market
    username: postgres
    password: admin